build: false
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27-django18"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27-django19"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27-django110"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27-django111"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34-django18"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34-django19"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34-django110"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34-django111"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34-django20"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35-django18"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35-django19"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35-django110"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35-django111"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35-django20"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35-django21"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35-django22"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36-django111"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36-django20"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36-django21"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36-django22"
    - PYTHON: "C:\\Python37"
      TOXENV: "py37-django20"
    - PYTHON: "C:\\Python37"
      TOXENV: "py37-django21"
    - PYTHON: "C:\\Python37"
      TOXENV: "py37-django22"
matrix:
  fast_finish: true
install:
  - "%PYTHON%\\python.exe -m pip install tox==3.14.0"
test_script:
  - "%PYTHON%\\python.exe -m tox"
