# Use the faster container-based infrastructure.
sudo: false
language: python
cache: pip
install:
  - pip install tox==3.18.1
matrix:
  allow_failures:
    # Django master is allowed to fail.
    - env: TOXENV=py36-master
    - env: TOXENV=py37-master
    - env: TOXENV=py38-master
  fast_finish: true
  include:
    - env: TOXENV=py37-lint
      python: 3.7
    - env: TOXENV=py35-django111
      python: 3.5
    - env: TOXENV=py35-django20
      python: 3.5
    - env: TOXENV=py35-django21
      python: 3.5
    - env: TOXENV=py35-django22
      python: 3.5
    - env: TOXENV=py36-django111
      python: 3.6
    - env: TOXENV=py36-django20
      python: 3.6
    - env: TOXENV=py36-django21
      python: 3.6
    - env: TOXENV=py36-django22
      python: 3.6
    - env: TOXENV=py36-django30
      python: 3.6
    - env: TOXENV=py36-django31
      python: 3.6
    - env: TOXENV=py36-master
      python: 3.6
    - env: TOXENV=py37-django20
      python: 3.7
    - env: TOXENV=py37-django21
      python: 3.7
    - env: TOXENV=py37-django22
      python: 3.7
    - env: TOXENV=py37-django30
      python: 3.7
    - env: TOXENV=py37-django31
      python: 3.7
    - env: TOXENV=py37-master
      python: 3.7
    - env: TOXENV=py38-django20
      python: 3.8
    - env: TOXENV=py38-django21
      python: 3.8
    - env: TOXENV=py38-django22
      python: 3.8
    - env: TOXENV=py38-django30
      python: 3.8
    - env: TOXENV=py38-django31
      python: 3.8
    - env: TOXENV=py38-master
      python: 3.8
script: tox -v
