# Use the faster container-based infrastructure.
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
install: travis_retry pip install 'requests>=2.11,<2.12' $DJANGO_VERSION
env:
  global:
    - PYTHONWARNINGS=all DJANGO_SETTINGS_MODULE=tests.django_settings
  matrix:
    - DJANGO_VERSION='Django>=1.8,<1.9'
    - DJANGO_VERSION='Django>=1.9,<1.10'
    - DJANGO_VERSION='Django>=1.10,<1.11'
    - DJANGO_VERSION='Django>=1.11a1,<2.0'
matrix:
  include:
    - python: 3.3
      env: DJANGO_VERSION='Django>=1.8,<1.9'
    # Python 3.6 is only officially supported by Django 1.11+.
    - python: 3.6
      env: DJANGO_VERSION='Django>=1.11a1,<2.0'
    # Django 2.0 only supports Python 3.5+.
    - python: 3.5
      env: DJANGO_VERSION=https://github.com/django/django/archive/master.tar.gz
    - python: 3.6
      env: DJANGO_VERSION=https://github.com/django/django/archive/master.tar.gz
    - python: 2.7
      env: lint
      install: travis_retry pip install flake8==3.0.4
      script: flake8 --show-source
  allow_failures:
    # Django master is allowed to fail
    - env: DJANGO_VERSION=https://github.com/django/django/archive/master.tar.gz
  fast_finish: true
script: python -m unittest discover
