# Use the faster container-based infrastructure.
sudo: false
language: python
dist: xenial
cache: pip
install:
  - pip install tox
matrix:
  allow_failures:
    # Django master is allowed to fail.
    - env: TOXENV=py35-master
    - env: TOXENV=py36-master
    - env: TOXENV=py37-master
  fast_finish: true
  include:
    - env: TOXENV=py27-lint
      python: 2.7
    - env: TOXENV=py27-django18
      python: 2.7
    - env: TOXENV=py27-django19
      python: 2.7
    - env: TOXENV=py27-django110
      python: 2.7
    - env: TOXENV=py27-django111
      python: 2.7
    - env: TOXENV=pypy-django18
      python: pypy2.7-5.10.0
    - env: TOXENV=pypy-django19
      python: pypy2.7-5.10.0
    - env: TOXENV=pypy-django110
      python: pypy2.7-5.10.0
    - env: TOXENV=pypy-django111
      python: pypy2.7-5.10.0
    - env: TOXENV=py34-django18
      python: 3.4
    - env: TOXENV=py34-django19
      python: 3.4
    - env: TOXENV=py34-django110
      python: 3.4
    - env: TOXENV=py34-django111
      python: 3.4
    - env: TOXENV=py34-django20
      python: 3.4
    - env: TOXENV=py35-django18
      python: 3.5
    - env: TOXENV=py35-django19
      python: 3.5
    - env: TOXENV=py35-django110
      python: 3.5
    - env: TOXENV=py35-django111
      python: 3.5
    - env: TOXENV=py35-django20
      python: 3.5
    - env: TOXENV=py35-master
      python: 3.5
    - env: TOXENV=py36-django111
      python: 3.6
    - env: TOXENV=py36-django20
      python: 3.6
    - env: TOXENV=py36-master
      python: 3.6
    - env: TOXENV=py37-django20
      python: 3.7
    - env: TOXENV=py37-master
      python: 3.7
script: tox -v
